### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by jinder** [Reklino/angular-resizable#1]
Thanks for the great directive.  I've played with your library somewhat and found a few issues that I've fixed.  However, unfortunately my corporate firewall doesn't allow me to submit a PR, so I will highlight them here:
1. 'rg-top' has an incorrect 'left' value.  'left' should change from 50% to 0.
2. Dragging can cause the selection of elements in the panel.  This can be disabled by adding the following to the bottom of dragStart:
   
   ```
           if(e.stopPropagation) e.stopPropagation();
           if(e.preventDefault) e.preventDefault();
           e.cancelBubble=true;
           e.returnValue=false;
   ```
3. If you have height or width animations on the resizable div, it won't work smoothly.  To fix this, add a no-transition class to the css:
   
   ```
   .resizable.no-transition {
   transition: none !important;
   }
   ```
   
   Then toggle it on in dragStart, and toggle it off in mouseup using the element.add/removeClass();

**Comment by Reklino** [comment]
Gotta love corporate firewalls... Thanks for doing the hard work @jinder!

The issues have been fixed using your suggestions on the latest commit. Here they are in a live test as well http://codepen.io/Reklino/pen/yymMWN?editors=101
