### ISSUE TITLE
Create new release with new implementation

### ISSUE THREAD

**Issue by cphyc** [Reklino/angular-resizable#12]
Would it be possible to create a new release at commit 6d0fbc769d4bf9489459f26165b9b75ac912f923 ?

**Comment by Reklino** [comment]
Hey @cphyc :). Do you mean like a major version change? If so, what are the benefits of doing so?

**Comment by cphyc** [comment]
That or a tag! I'm using the project as a bower dependency so it's always nicer to have a tag/version number instead of a SHA1.

**Comment by Reklino** [comment]
Okay, I've drafted a new release. Let me know if that helps. This is my first time handling versions and releases on github, so if I do anything weird feel free to call me out :).

**Comment by cphyc** [comment]
Thanks!
