### ISSUE TITLE
Drag-area appears under scrollbar when overflow auto is used

### ISSUE THREAD

**Issue by nvernooy** [Reklino/angular-resizable#13]
I just want to say this is a really great project and I've been finding it very helpful. I'm just having a problem with my scrollable content. I'm using a flex row layout with two div's side by side. Both are scrollable with overflow: auto in their styling. 
This issue arises when I add the resizable direcitve to the left div and setting the drag direction to right. The appended rg-right div appears under the scrollable area and the user first has to scroll to it to use it. When the content is resized the width of the enitire div stays longer than the scrollable area and the scrollbar stays.
When I tried to add the directive to the right content I could not see the drag-bar at all.
Do you perhaps have a solution for this?

**Comment by Reklino** [comment]
Hi @nvernooy. Glad you like the project :). Sounds like a CSS flexbox issue... I'm honestly no master of flexbox, but if you set up a codepen demonstrating your issue, I'll be happy to see if I can help!

**Comment by nvernooy** [comment]
Hi @Reklino, sorry but I ended up just going with jquery.
Don't know if you want to keep this issue open or not...

**Comment by Reklino** [comment]
No problem :). Whatever gets the job done man.
