### ISSUE TITLE
Usage with ngRepeat

### ISSUE THREAD

**Issue by omichelsen** [Reklino/angular-resizable#15]
Hi I'm curious if you have a suggestion for using your directive with ngRepeat. Specifically I want drag handles to the right of each box, except for the last one, but I see no way of disabling the directive on the last element?

**Comment by patlux** [comment]
https://github.com/Reklino/angular-resizable/pull/14

```
r-disabled="{{ $last }}"
```

**Comment by omichelsen** [comment]
Thanks. Combined it with this CSS to also hide it:

```
&:last-child {
    .rg-right, .rg-left {
        display: none;
    }
}
```
