### ISSUE TITLE
Safari and flexbox doesn't work

### ISSUE THREAD

**Issue by omichelsen** [Reklino/angular-resizable#16]
Since Safari <=8 still uses the vendor prefix `webkitFlexBasis`, resizing doesn't work.

Solution would be to do feature detection and choose the correct property.

**Comment by mattsawyer77** [comment]
Just tried your codepen demo on Safari 8.0.8. The layout is broken, and the resizing handles don't work.

**Comment by Reklino** [comment]
@mattsawyer77 right you are sir. I just fixed it by enabling 'autoprefixer' in the pen. Safari still requires -webkit- prefix for flexbox.

**Comment by mattsawyer77** [comment]
nice. the flexbox looks right now, but the handles don't seem to be draggable.

**Comment by Reklino** [comment]
Yep. You're right. Just updated with the latest version. Working fine now :)
