### ISSUE TITLE
Get original event inside resizable events

### ISSUE THREAD

**Issue by arcadeJHS** [Reklino/angular-resizable#18]
Is it possible to get the original javascript event inside, for instance, "angular-resizable.resizeEnd"?

**Comment by Reklino** [comment]
Something like [this](http://codepen.io/Reklino/pen/bdvgyW)? See the console for the event object...

**Comment by arcadeJHS** [comment]
Yes exactly the solution I've come up by working on your source!
Do you think you'll update the officia repository too?
Thx!

**Comment by Reklino** [comment]
Just updated the repo :)

**Comment by arcadeJHS** [comment]
Thank you!
