### ISSUE TITLE
Scope model inside resize events?

### ISSUE THREAD

**Issue by arcadeJHS** [Reklino/angular-resizable#19]
I would like to know if possible to retrieve scope model inside resizeStart/resizeEnd events.
For instance: I am using angular-resizable inside a ng-repeat, and I would like to operate on the underlying model on resizeEnd.
Is it possible to add custom params to resize events?
Obviously, we always have the option of something like: angular.element(e.target).scope()...
Or maybe it's simpler just to wrap the resizable object into a directive linked to the model (which is maybe the best solution).

Thank you very much!

**Comment by Reklino** [comment]
Hm... I'll have to take a further look at this later. In the meantime, feel free to create an example use case on codepen or something if you get time :)

**Comment by arcadeJHS** [comment]
Actually I am wrapping the resizable into a custom directive which link it to the underlying model.
Basically, inside the custom directive I listen to resizable events and link them to callback functions defined in the parent controller.
Something like:

``` html
<div ng-repeat="item in items" drag-resize-wrapper="item" on-item-move="onItemMove(e, items)" on-item-endmove="onItemEndMove(e, item)"></div>           
```

``` javascript
angular.module('app').directive('dragResizeWrapper', function() {

    return {        
        restrict: 'EA',
        replace: true,
        templateUrl: 'drag-resize-wrapper.html',            
        scope: {
            item: '=dragResizeWrapper',
            onItemMove: '&',
            onItemsEndmove: '&'
        },
        link: function(scope, elem, attrs) {
            scope.onMove = function(e) {
                scope.onItemMove({e: e, item: scope.item});
            };

            scope.onEndMove = function(e) {
                scope.onItemEndmove({e: e, item: scope.item});
            };              

            scope.$on("angular-resizable.resizing", function (event, args) {
                scope.onMove(args.evt);
            });

            scope.$on("angular-resizable.resizeEnd", function (event, args) {
                scope.onEndMove(args.evt);
            });
        }       
    };

});         
```

**Comment by Reklino** [comment]
I think your solution is clever, and it looks like it will work fine. I'm open to other ways to handle this... but for now I'm going to close this issue with your wrapper directive being the solution for now.
