### ISSUE TITLE
Width/height should be obtained at dragStart

### ISSUE THREAD

**Issue by jinder** [Reklino/angular-resizable#2]
Hi, me again!

I've got some resizable panels whose height can change prior to them being resized.  This results in the w/h values being incorrect because they're not updated until the mouseup event is captured.  Is there any reason why these aren't set in dragStart?  This also negates the need for them to be set on mouseup.

**Comment by Reklino** [comment]
Hey @jinder!

See if this [demo](http://codepen.io/Reklino/pen/zGxXxa) is what you were looking for.
If so, let me know and I'll push up changes.

**Comment by jinder** [comment]
Perfect - those are the exact modifications I've made on my local copy.  Apologies again for being unable to submit a PR!

**Comment by jinder** [comment]
Please also consider publishing this to NPM, I think it's great and simple - more people need to see it :)

**Comment by Reklino** [comment]
Issue fixed. I have also published it to NPM as you suggested.
Hopefully more people will find it. Thanks for the support :)
