### ISSUE TITLE
Angular Dependency in bower.json

### ISSUE THREAD

**Issue by PhilippSoehnlein** [Reklino/angular-resizable#22]
Hi,

the bower.json states that angular-resizable works with Angular 1.3, which leads to a resolution request by bower when you do a `bower install` in a project which uses Angular 1.4. 
Because I doubt that there are real compatibility problems with Angular != 1.3 (and Angular < 2) I would recommend to set the version statement in bower.json to 1.*.

**Comment by Reklino** [comment]
Merged your pull request. Thanks @PhilippSoehnlein :)
