### ISSUE TITLE
events are only being $emitted, should they also be $broadcasted

### ISSUE THREAD

**Issue by eddedd88** [Reklino/angular-resizable#25]
I was trying to resize a table inside of a resizable container by trying to hook into the 'resizeEnd' event.

My solution was to catch the event at the top controller and then $broadcast an event.

Would it be better if this component also broadcasted these events instead of having them to echo back?

**Comment by Reklino** [comment]
Hm... Because of the directive's isolated scope, we'd have to use

``` javascript
scope.$parent.$broadcast('angular-resizable.resizeStart', info);
```

I don't see why this should cause any issues though. See [this pen](http://codepen.io/Reklino/pen/VvxeKz/) for an example of how to implement it yourself. I'll add this to the enhancements for the next version.
