### ISSUE TITLE
Dynamic directions values

### ISSUE THREAD

**Issue by jedfoster** [Reklino/angular-resizable#29]
I've got angular-resizable working very well on my app, thank you! Now I'm trying to wire it up to user preferences; e.g. a user can change the orientation of resizable panels on the page.

Using this, `r-directions="[(preferences.orientation === 'vertical' ? 'bottom' : 'right')]"`, I am able to set the orientation correctly on the initial page load (`preferences` is an object stored in `localStorage`), but I don't see a way to make angular-resizable respond to changes to that scope property after the initial load. Is there a way to make angular-resizable re-render itself?

Thanks!

**Comment by jedfoster** [comment]
FWIW, I came up with this:

``` javascript
    return {
            restrict: 'AE',
            scope: {
                rDirections: '@',
                // ...
            },
            link: function(scope, element, attr) {
                // ...

                scope.$watch("rDirections", function(directions) {
                  if(typeof directions === 'string') {
                    dir = directions.split(',');
                  }

                  var oldGrabbers = element[0].querySelectorAll('[class^="rg-"]');
                  var l = oldGrabbers.length;
                  for (i = 0; i < l; ++i) {
                    var grabber = oldGrabbers[i];
                    grabber.parentNode.removeChild(grabber)
                  }

                  dir.forEach(function (direction) {
                      var grabber = document.createElement('div');

                      // add class for styling purposes
                      grabber.setAttribute('class', 'rg-' + direction);
                      grabber.innerHTML = inner;
                      element[0].appendChild(grabber);
                      grabber.ondragstart = function() { return false; };
                      grabber.addEventListener('mousedown', function(e) {
                          var disabled = (scope.rDisabled === 'true');
                          if (!disabled && e.which === 1) {
                              // left mouse click
                              dragStart(e, direction);
                          }
                      }, false);
                  });
                });
            }
        };
    });
```

Which allows me to use this in the template: `r-directions="{{editorOrientation()}}"`, where `editorOrientation` performs the necessary property checking and returns a string for the desired direction. It works well enough for my purposes, but I'm still curious if there's a better, more "Angular" way to accomplish this.

**Comment by Dilatorily** [comment]
+1

**Comment by Reklino** [comment]
Hey @jedfoster ! Nice work :). Based on your concept, I built out a [codepen](http://codepen.io/Reklino/pen/ZbxqMx/) that I think demonstrates what you're requesting. Take a look and let me know what you think! To toggle the resize directions, just click on the checkboxes in the upper left.

**Comment by jedfoster** [comment]
That codepen looks good to me. Thanks!
