### ISSUE TITLE
Have any option for resize?

### ISSUE THREAD

**Issue by truyen93** [Reklino/angular-resizable#36]
Hi,
Have any option for how object will be resize. I mean I just want to resize the left side while keep right side.
like your demo
http://codepen.io/Reklino/pen/zGxXxa

Thank!!

**Comment by Reklino** [comment]
For anyone else who finds this issue with the same question, the solution lies in adjusting the `r-centered-x` and/or `r-centered-y` attributes. When the element is centered, the velocity of the resize needs to be two-fold to keep up with the cursor. It's kinda weird to think about, but you'll notice when you play around with it.
