### ISSUE TITLE
Mouseup not raised if mouse is over an iframe

### ISSUE THREAD

**Issue by jinder** [Reklino/angular-resizable#5]
I've spent an hour or so trying to figure out why the resizer was sticking on some occasions.    If you click the resizer, and quickly move it while letting go of the mouse over an iframe, the mouseup event never gets called.  That means if you want to release the resizer, you have to click again.

I've tried a quick few hacks to fix this, and I can't see how to do it easily if you're using a cross-origin iframe.  The only thing I can think of, is to add an element to cover the entire screen while dragging, to make sure the events are raised on the current document.

Any ideas?  If not, I'll try and make the modifications and submit the code here.

**Comment by Reklino** [comment]
Ah interesting. I'm guessing you're losing the document mouseup event by hovering over the iframe (which has its own document). Here's a handy [stackoverflow thread](http://stackoverflow.com/questions/5645485/detect-mousemove-when-over-an-iframe) with a few solutions if haven't already seen it.

Just from glancing at it, the simplest solution may be to add a masking element while dragging like you suggested. Or, if you don't care about IE8/9, just use `pointer-events: none;` on the iframe during resize. I just pushed up changes that include **resize start and end events** that should make this possible. I'll work to put together an example with an iframe, but if you find a good solution in the meantime feel free to post the code :)

**Comment by jinder** [comment]
Pointer-events certainly works, so I think it's probably the best solution.  Could you publish the latest version to NPM too?  Thanks

**Comment by Reklino** [comment]
Yep. Sorry about that :P
