### ISSUE TITLE
Grabber is displayed over element when element height gets too small

### ISSUE THREAD

**Issue by jbadger** [Reklino/angular-resizable#8]
If you grab the vertical grabber above the image on http://codepen.io/Reklino/full/raRaXq/ and drag it up, eventually it will appear over section#two.  This is exacerbated if there is a min-height on the element.  It should always be shown beneath with no overlap.

![screen shot 2015-06-06 at 3 44 53 pm](https://cloud.githubusercontent.com/assets/1226033/8021782/075a00ac-0c63-11e5-8c91-3d24acc8143e.png)

**Comment by Reklino** [comment]
Hi @jbadger. This should be fixed in the demo now :)
