### ISSUE TITLE
Issue with sizes when you have inline relative size

### ISSUE THREAD

**Issue by cphyc** [Reklino/angular-resizable#9]
When you have a relative size in an inline CSS attribute, for example

```
<div resizable r-directions="['left']" style="width: 70%">
  …
</div>
```

the resize events do not convert the size into the proper absolute size.

**Comment by Reklino** [comment]
Hey @cphyc. Sorry I'm so late getting to this. I can't seem to recreate this issue. It may be that I am misunderstanding the problem. Can you take a look at [this pen](http://codepen.io/Reklino/pen/BNwVER)? I have set an inline relative width on the resizable container and it seems to be reporting the correct pixel values via the events. Are you wanting it to report _relative_ values?

**Comment by cphyc** [comment]
Ok, that's weird, I can't reproduce it now…

**Comment by Reklino** [comment]
Lol. I know how that feels. Just let me know if you run into it again and we'll figure it out :)
